export const songMap = {
  "190": ["百九十", "百九十"],
  "A_Reincarnation_of_a_Scattering_Spring": ["樱落繁花", "樱落繁花"],
  "Aconsma": ["Aconsma"],
  "Agnostic": ["Agnostic"],
  "Akashinosakuracho": ["灯ノ桜蝶", "灯桜蝶"],
  "Aleph-0": ["Aleph-0"],
  "Algebra": ["Algebra"],
  "Ameonna": ["雨女", "雨女"],
  "Autumn_Rain": ["Autumn Rain", "AR"],
  "BUCHiAGE_Fireworks": ["BUCHiAGE Fireworks", "BF"],
  "Before_it_Ends": ["Before it Ends", "BIE"],
  "Betelgeuse": ["参宿四~Betelgeuse~", "参宿四"],
  "Bio-Engineering": ["Bio-Engineering"],
  "Blueface": ["☹"],
  "Brightened_Demonios": ["Brightened Demonios", "BD"],
  "Broken_Conviction": ["Broken Conviction", "BC"],
  "Castle_in_the_Rain": ["雨之城", "雨之城"],
  "Chartreuse_Green": ["Chartreuse Green", "CG"],
  "Contrasty_Angeles": ["Contrasty Angeles", "CA"],
  "Curse_of_14": ["Curse of 14"],
  "Deluge": ["Deluge"],
  "Dogbite": ["Dogbite"],
  "Dum_Dum_Dum": ["Dum! Dum!! Dum!!!"],
  "Elsorhg": ["Elsorhg"],
  "Episodic_Rain": ["时落之雨", "时落之雨"],
  "FULi_AUTO_SHOOTER": ["FULi AUTO SHOOTER", "FAS"],
  "Fantasia_Sonata_Arcadia": ["Fantasia Sonata Arcadia", "FSA"],
  "Fantasia_Sonata_Botanical_Garden": ["Fantasia Sonata Botanical Garden", "FSBG"],
  "Fantasia_Sonata_God_Dance": ["Fantasia Sonata God Dance", "FSGD"],
  "Fantasia_Sonata_Hope": ["Fantasia Sonata Hope", "FSH"],
  "Fantasia_Sonata_Reflection": ["Fantasia Sonata Reflection", "FSR"],
  "Fantasia_Sonata_Sky_Syndrome": ["Fantasia Sonata Sky Syndrome", "FSSS"],
  "Fantasia_Sonata_Stars": ["Fantasia Sonata Stars", "FSS"],
  "Fluorescent_Light": ["Fluorescent Light", "FL"],
  "Fly_To_Meteor_Milthm_Edit": ["Fly To Meteor (Milthm Edit)"],
  "Fly_To_Meteor_featTuQi_Milthm_Edit": ["Fly To Meteor feat.兔柒 (Milthm Edit)", "兔柒"],
  "Fragment_of_Memories": ["Fragment of Memories", "FOM"],
  "Future_Unbound_Game_Edit": ["Future Unbound (Game Edit)"],
  "Garden": ["Garden"],
  "GlassyHeart": ["GlassyHeart."],
  "HYPER_MEMORIES": ["HYPER MEMORIES", "HM"],
  "Hanten": ["はんてん"],
  "Hikari": ["Hikari"],
  "Hoshifuru_Yoruni": ["ホシフルヨルニ"],
  "IN": ["IN"],
  "INFPmp3": ["INFP.mp3"],
  "Imaginary_Tomorrow": ["仮想明日", "仮想明日"],
  "Innocent_white": ["Innocent white", "IW"],
  "Jump_out": ["Jump out?"],
  "KASANE": ["KASANE"],
  "Kagetsu": ["花月", "花月"],
  "Kayava": ["Kayava"],
  "LOUDER": ["LOUDER!"],
  "Meinichi": ["命日", "命日"],
  "Meltovt_Necrosys": ["Meltovt Necrosys", "MN"],
  "Moonfall": ["大月墜落狂想", "大月墜落狂想"],
  "Moonflutter": ["Moonflutter"],
  "Moving_On": ["Moving On", "MO"],
  "Myth_compiler": ["Myth compiler", "MC"],
  "Neon_Iro_no_Machi_feat_Mai": ["ネオン色のまち feat. Mai"],
  "Nini_feat_Qayo__mii": ["ニニ (feat. Qayo & mii)"],
  "Oiiaioooooiai": ["Oiiaioooooiai"],
  "Oniichan": ["Oniichan"],
  "OverRain": ["OverRain"],
  "Pieces_of_the_Cycle": ["サイクルの欠片", "欠片"],
  "Psyched_Fevereiro": ["Psyched Fevereiro", "PF"],
  "Pthahnil": ["Pthahnil"],
  "Rainbow_Flavor": ["Rainbow Flavor!"],
  "Rainshower": ["驟雨の狭間", "驟雨狭間"],
  "Regnaissance": ["Regnaissance"],
  "Rei": ["靈"],
  "Reminiscence_in_Starlight": ["暮予星光", "暮予星光"],
  "Sakuyahime": ["Sakuyahime"],
  "Sheer_Ice_Torrent": ["Sheer Ice Torrent", "SIT"],
  "Someday_I_will_Forget": ["いつか忘れるんだろう"],
  "Sound_of_Nature": ["Sound of Nature", "SON"],
  "Sparkrain": ["烁雨", "烁雨"],
  "Splash_the_Beat": ["Splash the Beat!!"],
  "Sundown": ["Sundown"],
  "Thick_Rain": ["粗线条的雨", "粗线条的雨"],
  "Threat_-_Metropolis": ["Threat - Metropolis"],
  "Threat_-_Sky_Islands": ["Threat - Sky Islands"],
  "Threat_-_Superstructure": ["Threat - Superstructure"],
  "Threat_-_Waterfront_Complex": ["Threat - Waterfront Complex"],
  "Tiger_Lotus": ["白虎蓮華", "白虎蓮華"],
  "Unmei": ["運命", "運命"],
  "Vestige_of_Dreams": ["Vestige of Dreams", "VOD"],
  "Virtual_S0da": ["Virtual S0da"],
  "WATER": ["WATER"],
  "Welcome_to_Milthm": ["Welcome to Milthm", "WTM"],
  "White_Lizard": ["White Lizard", "WL"],
  "Words": ["Words"],
  "Yokaze": ["夜風", "夜風"],
  "apOapSisEdit": ["apOapSis(Edit)"],
  "cafe_in_6412I731V": ["cafe in 6412I731V"],
  "conflict": ["conflict"],
  "cybernetic_blazar": ["cybernetic blazar", "CB"],
  "eclat": ["イコラト"],
  "slichertz_GdbG": ["slic.hertz #GdbG"],
};
